services:
  mc:
    image: itzg/minecraft-server:java17-graalvm
    tty: true
    stdin_open: true
    ports:
      - ${SERVER_PORT}:25565
    environment:
      ALLOW_FLIGHT: true
      ENABLE_COMMAND_BLOCK: true
      EULA: "TRUE"
      ONLINE_MODE: false
      RCON_CMDS_STARTUP: |-
        gamerule keepInventory true
        gamerule playersSleepingPercentage 51
      RCON_PASSWORD: ${RCON_PASSWORD}
      SEED: ${SEED}
      SNOOPER_ENABLED: false

      NEOFORGE_VERSION: "21.1.210"
      PACKWIZ_URL: ${MODPACK}
      TYPE: NEOFORGE
      VERSION: "1.21.3"

      INIT_MEMORY: 8G
      MAX_MEMORY: 20G
      USE_MEOWICE_FLAGS: true
      USE_MEOWICE_GRAALVM_FLAGS: true
    networks:
      - default
    volumes:
      - ${MNT_DATA}:/data
  bk:
    image: itzg/mc-backup:stable
    environment:
      BACKUP_ON_STARTUP: false
      INITIAL_DELAY: 5m
      PAUSE_IF_NO_PLAYERS: true
      PLAYERS_ONLINE_CHECK_INTERVAL: 1h
      RCON_HOST: mc
      RCON_PASSWORD: ${RCON_PASSWORD}

      BACKUP_METHOD: restic
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
    networks:
      - default
    volumes:
      - ${MNT_DATA}:/data:ro
      - ${MNT_BACKUP}:/backups
networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
